// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasevski.Services.ProductAPI.DbContexts;

namespace Tasevski.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211019084851_AddPrikaziToProdukt")]
    partial class AddPrikaziToProdukt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.7.21378.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tasevski.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Prikazi")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Готвени јадења",
                            Description = "Вкусни телешки шницли кои ќе ги обожавате. Добар апетит!",
                            ImageUrl = "https://dotnettasevski.blob.core.windows.net/tasevskirestaurant/Sliki/meso-snicla.jpg",
                            Name = "Tелешки шницли во сос",
                            Price = 450.0,
                            Prikazi = false
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Готвени јадења",
                            Description = "Ароматични компири со рузмарин. Добар апетит!",
                            ImageUrl = "https://dotnettasevski.blob.core.windows.net/tasevskirestaurant/Sliki/kompiri-tava.jpg",
                            Name = "Вкусни ароматични компири",
                            Price = 250.0,
                            Prikazi = false
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Јадења по порачка",
                            Description = "Навистина брз, вкусен и здрав оброк. Добар апетит!",
                            ImageUrl = "https://dotnettasevski.blob.core.windows.net/tasevskirestaurant/Sliki/spanak-jajca.jpg",
                            Name = "Здрав оброк од спанаќ и јајца",
                            Price = 180.0,
                            Prikazi = false
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Вкусно и сочно мешано месо. Добар апетит!",
                            ImageUrl = "https://dotnettasevski.blob.core.windows.net/tasevskirestaurant/Sliki/pilesko.jpg",
                            Name = "Мешано месо во вкусен сос",
                            Price = 350.0,
                            Prikazi = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
